# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('capital_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=250)),
                ('Places', models.CharField(max_length=250)),
                ('Religion', models.CharField(max_length=100)),
                ('Places_pic_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='capital',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Country.State'),
        ),
    ]
